name: linux

on:
  push:
    tags:
      - '**'
    branches-ignore:
      - pages

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: NPM
        run: npm ci

      - name: shockpkg
        run: |
          npm exec shockpkg -- update --summary
          npm exec shockpkg -- install \
            flash-player-11.2.202.644-linux-i386-sa-debug \
            flash-player-32.0.0.465-linux-x86_64-sa-debug
        shell: bash

      - name: Build i386
        run: node make.mjs build:linux-i386

      - name: Build x86_64
        run: node make.mjs build:linux-x86_64

      - name: Dist i386 tgz
        run: node make.mjs dist:linux-i386:tgz

      - name: Dist x86_64 tgz
        run: node make.mjs dist:linux-x86_64:tgz

      - name: Artifact build
        uses: actions/upload-artifact@v3
        with:
          name: linux-build
          path: build/

      - name: Artifact dist
        uses: actions/upload-artifact@v3
        with:
          name: linux-dist
          path: dist/

      - name: Deploy
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: dist/*
