name: mac

on:
  push:
    tags:
      - '**'
    branches-ignore:
      - pages
  pull_request:

jobs:
  build:
    runs-on: macos-latest
    env:
      SHOCKPKG_PACKAGES: >-
        flash-player-35.0.0.60-mac-x86_64-arm64-sa-2023-09-23
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: NPM
        run: npm ci

      - name: shockpkg Cache
        uses: actions/cache@v3
        with:
          key: shockpkg ${{ env.SHOCKPKG_PACKAGES }}
          path: shockpkg

      - name: shockpkg Update
        run: npm exec shockpkg -- update --summary

      - name: shockpkg Install
        run: npm exec shockpkg -- install ${{ env.SHOCKPKG_PACKAGES }}

      - name: Build
        run: node make.mjs build:mac-x86_64-arm64

      - name: Dist tgz
        run: node make.mjs dist:mac-x86_64-arm64:tgz

      - name: Dist dmg
        run: node make.mjs dist:mac-x86_64-arm64:dmg

      - name: Artifact build
        uses: actions/upload-artifact@v3
        with:
          name: mac-build
          path: build/

      - name: Artifact dist
        uses: actions/upload-artifact@v3
        with:
          name: mac-dist
          path: dist/

      - name: Deploy
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: dist/*
