name: windows

on:
  push:
    tags:
      - '**'
    branches-ignore:
      - pages
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    env:
      SHOCKPKG_PACKAGES: >-
        flash-player-35.0.0.204-windows-i386-sa-2022-08-13
        flash-player-35.0.0.204-windows-x86_64-sa-2022-08-13
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: NPM
        run: npm ci

      - name: shockpkg Cache
        uses: actions/cache@v3
        with:
          key: shockpkg ${{ env.SHOCKPKG_PACKAGES }}
          path: shockpkg

      - name: shockpkg Update
        run: npm exec shockpkg -- update --summary

      - name: shockpkg Install
        run: npm exec shockpkg -- install ${{ env.SHOCKPKG_PACKAGES }}

      - name: Build i386
        run: node make.mjs build:windows-i386

      - name: Build x86_64
        run: node make.mjs build:windows-x86_64

      - name: Dist i386 zip
        run: node make.mjs dist:windows-i386:zip

      - name: Dist x86_64 zip
        run: node make.mjs dist:windows-x86_64:zip

      - name: Dist i386 exe
        run: node make.mjs dist:windows-i386:exe

      - name: Dist x86_64 exe
        run: node make.mjs dist:windows-x86_64:exe

      - name: Artifact build
        uses: actions/upload-artifact@v3
        with:
          name: windows-build
          path: build/

      - name: Artifact dist
        uses: actions/upload-artifact@v3
        with:
          name: windows-dist
          path: dist/

      - name: Deploy
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: dist/*
